version: "3.7"

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    expose:
      - 8000
      - 9000
    # ports:
    #   - 8000:8000
    #   - 9000:9000
    restart: unless-stopped

volumes:
  portainer_data:
