version: "3.7"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    expose:
      - 8000
      - 9000
    networks:
      - reverse-proxy
      - utils
    restart: unless-stopped

volumes:
  portainer-data:
    name: portainer-data

networks:
  reverse-proxy:
    external: true
  utils:
    name: utils
